stages:
- stage: x64
  displayName: 'Build x64'
  dependsOn: []
  jobs:
  - template: jobs/build.yml
    parameters:
      arch: x64

- stage: arm64
  displayName: 'Build arm64'
  dependsOn: []
  jobs:
  - template: jobs/build.yml
    parameters:
      arch: arm64

- stage: Package
  displayName: 'Package'
  dependsOn:
  - x64
  - arm64
  jobs:
  - template: jobs/package.yml
  condition: ne( variables['VERSION'], '' )
